train:
  _target_: src.datasets.Dataset
  part: "train"
  data_dir: "../../input/dla-dataset/dla_dataset"
  save_dir: "save_dir"
  limit: 1
val:
  _target_: src.datasets.Dataset
  part: "train"
  data_dir: "../../input/dla-dataset/dla_dataset"
  save_dir: "save_dir"
  limit: 1