device: "auto"
train: [ ]
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISNR
    name: "SI-SNR"
  - _target_: src.metrics.SISNRi
    name: "SI-SNRi"
  - _target_: src.metrics.SDRi
    name: "SDRi"
