_target_: src.model.RTFS
R: 4
n_speakers: 2
channel_dim: 392
n_fft: 256
hop_length: 128
video_embed_dim: 512
fusion_n_head: 4
hidden_dim: 64
freqs: 128
q_audio: 2
q_video: 4
use_video: False
lipreading_model_path: "./data/other/lipreading_model.pth"
