defaults:
  - model: calculate_bonus
  - writer: cometml
  - metrics: inference
  - datasets: calculate_bonus_inf
  - dataloader: calculate_bonus
  - transforms: example
  - _self_
inferencer:
  device_tensors: [ "mix", "source", "video" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  save_path: "tmp"
  is_amp: True