defaults:
  - model: rtfs
  - metrics: inference
  - datasets: inference
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: [ "mix", "source", "video" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  save_path: "tmp"
  from_pretrained: "data/other/R12.pth"
  is_amp: True
